### PR TITLE
Hello world project with two apps

### PR DESCRIPTION
**Pull request by eerapheal**
## Learning objectives
Implement a connection between a Ruby on Rails back-end and React front-end.
Understand the pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

## Link to frontend:
https://github.com/eerapheal/frontends/pull/2

## Built with:
- RonR
- React/Redux
- Cors

### CODE REVIEW

**Review by Reem-lab — COMMENTED** [review]
Hi @eerapheal, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have :


- [ ] And you should submit a PR in the front end project not the gihub link you should also make a PR in your front end repo som please create a PR in the front end repo with linters set up and put the PR link here in the backend PR ✨

- [ ] I noticed you are missing key features section so please add 1 to 3 key features for this project and future features section since it is very important to add them to have a professional README 🔥 kindly do the same for the front end repo 🙏🏻✨


- [ ] you have a live demo section in your README file and to have a professional README file you should remove this section till you have your app deployed so you can just add the live demo section in case you have deployed link for your project is present. .✅❗💯🤩✨✨ kindly do the same for the front end repo 🚀🙏🏻

- [ ]  I am not be able to see a title or a description in the README so kindly add it 💯🤩 to have a professional README 💯 kindly do the same for the front end repo 🚀


- [ ] A PR with not complete files since you merged most of the project files and  you should not merge till you get the approval so please submit a PR with all the files changes to let the reviewer be able to review you project and add comments if there is any? 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by eerapheal** [comment]
@Reem-lab Thanks for the comment but this is hello rails backend and react front end. Deployment of the project is required.

**Comment by eerapheal** [comment]
@Reem-lab checks is giving me issues for days now.

**Comment by Reem-lab** [comment]
Hello @eerapheal if it is required then you can add the deployed link ✨✨🔥

**Comment by eerapheal** [comment]
@Reem-lab kindly point out for me where deployment is required.
[Project requirement](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/hello_world_two_apps.md)

**Comment by Reem-lab** [comment]
Hello @eerapheal i think didn't say that it is required I just mentioned that you should remove the live demo section since there is no deployed link or no requirements says that you should deploy it so please  just remove that section 🔥✨🙏🏻, I hope it is clear now and if there is any issues please let me know

**Comment by rloterh** [comment]
Hi @eerapheal 
Can you remove this aspect from from your ReadMe asap!
image

**Comment by rloterh** [comment]
Please, also do the same for the frontend!

Cheers!

**Comment by eerapheal** [comment]
@rloterh done. Thanks.

**Comment by rloterh** [comment]
Oh one more ..let correct here too!

image

Please do the same correction for your forntend repo as well. Thanks 🙏

**Comment by rloterh** [comment]
@eerapheal 
Key Features in your ReadMe is still blank
Kindly add some features of your project under your Key Features section

I urge you to also ensure that the MIT license link is not broken

Cheers!

**Review by rloterh — COMMENTED** [review]
Hi Raphael, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented:
- [ ] Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe (for both frontend and backend repo). 
- [ ] All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.
- [ ]  The **_Key Features_** section of your ReadMe includes 1-3 features  of your project. (Also for the frontend ReadMe)
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
